"""Render the two evidence stories as complete, script-independent HTML."""
import json
import re
from html import escape as e
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / 'dist'
COPY = json.loads((ROOT / 'docs/access-story-copy.json').read_text())
SOURCES = {
    'hud': 'https://www.hud.gov/helping-americans/housing-choice-vouchers-tenants',
    'furman': 'https://www.furmancenter.org/wp-content/uploads/ee-legacy/Success_Rates_in_the_Housing_Choice_Voucher_Program_508.pdf',
    'urban': 'https://www.urban.org/research/publication/pilot-study-landlord-acceptance-housing-choice-vouchers',
    'trial': 'https://opportunityinsights.org/paper/cmto/',
    'jama': 'https://jamanetwork.com/journals/jama/fullarticle/2821639',
    'oig': 'https://oig.hhs.gov/reports/all/2025/many-medicare-advantage-and-medicaid-managed-care-plans-have-limited-behavioral-health-provider-networks-and-inactive-providers/',
    'medicaid': 'https://www.medicaid.gov/medicaid/managed-care',
}
NAV = '<a href="/case-studies/wic/">WIC <small>Read the story</small></a><a href="/case-studies/housing/">Housing vouchers <small>Read the story</small></a><a href="/case-studies/health/">Medicaid mental-health access <small>Read the story</small></a>'
HEADER = '<header class="global-header"><a class="brand" href="/">Available ≠ Accessible</a><nav aria-label="Main navigation"><a href="/">Home</a><details class="case-menu"><summary>Case studies<svg class="nav-chevron" width="12" height="12" viewBox="0 0 12 12" aria-hidden="true"><path d="m2 4 4 4 4-4" fill="none" stroke="currentColor" stroke-width="1.5"/></svg></summary><div>' + NAV + '</div></details><a href="/support/">Find support</a><a href="/about/">About Megan</a></nav></header>'

HOUSE = '''<svg viewBox="0 0 500 440" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="266" cy="385" rx="192" ry="19" fill="#29352f" opacity=".07"/><path d="M189 182 313 89l128 93v195H189Z" fill="#f8f6f0" stroke="#29352f" stroke-width="3"/><path d="m170 193 143-110 147 110" stroke="#29352f" stroke-width="10" stroke-linecap="round"/><path d="M326 261h63v116h-63z" fill="#9b432e"/><circle cx="376" cy="324" r="4" fill="#eee6ce"/><path d="M227 209h61v61h-61zM343 204h53v32h-53z" fill="#b7cbd0" stroke="#29352f" stroke-width="2"/><path d="M258 209v61m-31-31h61" stroke="#29352f" stroke-width="2"/><g transform="rotate(-9 126 280)"><rect x="35" y="175" width="183" height="212" rx="3" fill="#eee6ce" stroke="#29352f" stroke-width="2"/><text x="56" y="205" font-family="sans-serif" font-size="10" letter-spacing="2" fill="#29352f">RENTAL ASSISTANCE</text><text x="56" y="248" font-family="sans-serif" font-size="29" fill="#29352f">Housing</text><text x="56" y="280" font-family="sans-serif" font-size="29" fill="#29352f">voucher</text><path d="M57 310h129m-129 15h100m-100 15h116" stroke="#81866f"/><rect x="65" y="352" width="129" height="26" rx="2" stroke="#9b432e" stroke-width="2"/><text x="80" y="369" font-family="sans-serif" font-size="12" letter-spacing="2" fill="#9b432e">APPROVED</text></g><path d="M410 75v-23m-29 35-13-18m57 19 17-15" stroke="#9b432e" stroke-width="3" stroke-linecap="round"/></svg>'''
HEALTH = '''<svg viewBox="0 0 500 440" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="248" cy="389" rx="198" ry="17" fill="#29352f" opacity=".07"/><g transform="rotate(7 336 240)"><rect x="231" y="121" width="204" height="253" rx="10" fill="#f8f6f0" stroke="#29352f" stroke-width="2"/><path d="M232 169h202" stroke="#29352f" stroke-width="2"/><path d="M270 106v29m126-29v29" stroke="#29352f" stroke-width="8" stroke-linecap="round"/><text x="259" y="157" font-family="sans-serif" font-size="13" letter-spacing="2" fill="#265e74">APPOINTMENT</text><g stroke="#c1ccc4" stroke-width="2"><path d="M260 194h147m-147 35h147m-147 35h147m-147 35h147m-147 35h147M260 194v140m37-140v140m37-140v140m36-140v140m37-140v140"/></g><circle cx="350" cy="282" r="24" stroke="#9b432e" stroke-width="3"/><text x="343" y="289" font-family="sans-serif" font-size="22" fill="#9b432e">?</text></g><g transform="rotate(-8 173 235)"><rect x="33" y="153" width="275" height="178" rx="15" fill="#265e74" stroke="#29352f" stroke-width="2"/><text x="58" y="186" font-family="sans-serif" font-size="12" letter-spacing="2" fill="#fff">HEALTH COVERAGE</text><text x="56" y="230" font-family="sans-serif" font-size="36" fill="#fff">Medicaid</text><rect x="57" y="251" width="36" height="28" rx="4" fill="#c9c3a5"/><path d="M58 265h33m-17-13v25" stroke="#928c71"/><text x="58" y="308" font-family="sans-serif" font-size="12" fill="#fff">COVERED. NOW FIND CARE.</text></g><path d="M167 103c0-27 39-31 44-7 4 19-20 19-20 35m0 13v3" stroke="#265e74" stroke-width="5" stroke-linecap="round"/></svg>'''
KEY = '''<svg class="key-art" viewBox="0 0 400 220" aria-hidden="true"><ellipse cx="208" cy="177" rx="135" ry="12" fill="#29352f" opacity=".06"/><g transform="rotate(-25 200 110)" fill="none" stroke="#9b432e" stroke-width="15" stroke-linejoin="round"><circle cx="119" cy="108" r="43"/><path d="M161 108h171v26m-34-26v34m-34-34v25"/></g><path d="m99 57-17-14m40 1V21" stroke="#29352f" stroke-width="3" stroke-linecap="round"/></svg>'''

def table(headers, rows):
    return '<table><thead><tr>'+''.join('<th scope="col">'+e(str(x))+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">' if i == 0 else '<td>')+e(str(x))+('</th>' if i == 0 else '</td>') for i,x in enumerate(row))+'</tr>' for row in rows)+'</tbody></table>'

def details(headers, rows, note=''):
    return '<details class="data-details"><summary>Data &amp; how to read it</summary>'+table(headers,rows)+'<p>'+e(note)+'</p></details>'

def figure(label, title, body, caption, data=''):
    return '<figure class="story-figure"><p class="figure-label">'+label+'</p><p class="figure-title">'+title+'</p>'+body+'<figcaption>'+caption+'</figcaption>'+data+'</figure>'

def icons(n, cls='', element='i'):
    return ''.join(f'<{element} class="{cls}" style="--i:{i%40}"></{element}>' for i in range(n))

def bar(label, value, maxval=100, suffix='%', cls=''):
    return f'<div class="bar-row {cls}"><div class="row-label"><span>{label}</span><b>{value}{suffix}</b></div><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="--v:{value/maxval*100}"></div></div></div>'

denials = [('Fort Worth',78),('Los Angeles',76),('Philadelphia',67),('Newark',31),('Washington, DC',15)]
trend = [(2018,65.7),(2019,65.5),(2020,65.7),(2021,58.0),(2022,57.3)]
waits = [('Phoenix',11),('Chicago',23),('New York City',28),('Los Angeles',64)]
housing = [
figure('01 / The benefit','Rental assistance. A search still ahead.', '<div class="voucher-art" aria-hidden="true"><small>HOUSING CHOICE</small><strong>Rental<br>voucher</strong><div class="ink-lines"></div><span class="stamp">APPROVED</span></div><p class="metric-caption">A local housing agency pays part of the rent. The household finds an eligible home.</p>', 'Illustrative voucher, not an official document. Program overview: HUD.'),
figure('02 / The process','Three parties. One home.', '<ol class="process"><li><div>Find a potential home<small>Household</small></div></li><li><div>Submit tenancy paperwork<small>Household + landlord</small></div></li><li><div>Inspect the home and review rent<small>Housing agency + landlord</small></div></li><li><div>Complete the lease and assistance arrangements<small>Household + landlord + housing agency</small></div></li></ol>', 'Simplified HUD process. These are steps, not measured dropout rates. Search deadlines and extensions depend on the housing agency.'),
figure('03 / Five study locations · report published 2018','When landlords said no', ''.join('<div class="door-row"><div class="row-label"><span>'+name+'</span><b>'+str(v)+'%</b></div><div class="door-strip" aria-hidden="true">'+icons(v,'denied')+icons(100-v)+'</div></div>' for name,v in denials)+'<div class="legend"><span>Voucher denied</span><span class="outline">Remainder</span></div>', 'Reported voucher-denial rates in five study locations. Denominator: acceptance tests used for each location’s rate. Each row shows 100 symbols using rounded percentages.', details(['Study location','Denial rate'],[(n,f'{v}%') for n,v in denials],'The remainder does not represent completed leases. Historical findings, not current city rankings. Source: Urban Institute / HUD pilot study.')),
figure('04 / New voucher searches · 2022','From assistance issued to a lease', '<div class="big-number">57.3<span>%</span></div><p class="metric-caption">leased a home within one year</p><div class="search-dots" aria-hidden="true">'+icons(57,'success')+icons(43)+'</div><div class="legend"><span>Leased within one year</span><span class="outline">Did not record that outcome</span></div><p class="chart-note">100 symbols, rounded to 57 filled. Exact estimate: 57.3%.</p><div class="trend" aria-hidden="true">'+''.join(f'<div style="--v:{v}"><b>{v:.1f}%</b><small>{year}</small></div>' for year,v in trend)+'</div>', 'United States · 1,232 housing agencies meeting data-quality standards. Denominator: searches by new tenant-based voucher recipients. A one-year research window is not a universal search allowance.', details(['Year','Leased within one year'],[(y,f'{v:.1f}%') for y,v in trend],'Furman Center, April 2025, Exhibit 3. Smaller and rural agencies are underrepresented. Records do not explain every unsuccessful search.')),
figure('05 / Separate randomized trial · Seattle & King County','Support can expand neighborhood choice',bar('Control group',15,cls='control')+bar('Group offered support',53)+'<div class="bar-axis" aria-hidden="true"><span>0%</span><span>100%</span></div><div class="support-chips"><span>Neighborhood information</span><span>Customized search help</span><span>Landlord connections</span><span>Short-term financial help</span></div>', 'Outcome: families moving to high-upward-mobility neighborhoods. Denominator: families in each experimental group. These are not overall lease-up rates.',details(['Experimental group','Moved to target neighborhoods'],[('Control','15%'),('Offered bundled support','53%')],'Creating Moves to Opportunity. This trial tests a bundle of help, not the isolated effect of any one component. Separate population and outcome from the preceding chart.')),
figure('06 / The question','What counts as delivery?',KEY+'<p class="finish-copy">From a voucher<br>to a place to live.</p>', 'Search → coordination → lease. A conceptual endpoint, not a claim that every household reached it.')]

health = [
figure('01 / The public benefit','Coverage begins the journey', '<div class="coverage-card" aria-hidden="true"><small>HEALTH COVERAGE</small><strong>Medicaid</strong><div class="card-chip"></div><p>Now find an appointment.</p></div><p class="metric-caption">A public benefit delivered through a network of care.</p>','Illustrative card. This story focuses on adult psychiatric prescribing appointments through Medicaid managed care.'),
figure('02 / Four-city audit · calls in 2023','320 listings. What happens next?', '<div class="city-groups">'+''.join('<div><h3>'+city+'</h3><div class="tile-grid" aria-hidden="true">'+icons(80)+'</div><small>80 sampled clinicians</small></div>' for city in ['New York City','Los Angeles','Chicago','Phoenix'])+'</div>', 'JAMA, published 2024. Psychiatric prescribing clinicians listed as accepting new patients in each city’s highest-enrollment Medicaid managed-care plan. Each tile represents one sampled listing.'),
figure('03 / Same 320 offices','87 offices offered an appointment', '<div class="big-number">27.2<span>%</span></div>'+''.join(f'<div class="outcome-group {cls}"><div class="row-label"><span>{label}</span><b>{n}</b></div><div class="tile-grid" aria-hidden="true">'+icons(n)+'</div></div>' for cls,label,n in [('primary','Selected clinician',57),('alternate','Alternate at the practice',30),('none','No appointment obtained',233)]), '57 + 30 = 87 appointment offers, out of 320 offices contacted. Each tile represents one office. An offer is not completed treatment.',details(['Outcome','Offices'],[('Selected clinician',57),('Alternate clinician',30),('No appointment obtained',233),('Total',320)],'JAMA four-city audit, 2023 calls. These are mutually exclusive outcomes, not stages of a funnel. An unsuccessful contact does not by itself establish fraud.')),
figure('04 / Offered appointments with recorded waits','And then, the wait.', '<div class="calendar-bars">'+''.join(bar(n,v,maxval=70,suffix=' days') for n,v in waits)+'</div><div class="bar-axis" aria-hidden="true"><span>0 days</span><span>70 days</span></div>', 'Median wait to an offered appointment, by city. Covers selected and alternate clinicians. Waits could not be recorded for 17 of the 87 offers without further registration.', details(['City','Median wait'],[(n,f'{v} days') for n,v in waits],'JAMA, Figure 1. 70 offers had recorded waits across the four cities. These are medians among observed offers, not all callers’ waiting times or a promise to an individual patient.')),
figure('05 / Recommendations, not a measured improvement','Measure the route to care', '<div class="accountability"><div><h3>Reachable?</h3><p>Does the directory lead to the right office?</p></div><div><h3>Available?</h3><p>Can the practice offer care through the plan?</p></div><div><h3>Timely?</h3><p>When is an appointment available?</p></div><div><h3>Supported?</h3><p>What happens if the first option does not work?</p></div></div>', 'Editorial access questions. Separate 2025 HHS inspector general review: CMS should work with states to improve Medicaid managed-care directory accuracy.')]

def lease_graphic():
    marks=[]
    for i in range(100):
        ok=i<57;j=i if ok else i-57
        x=(35 if ok else 300)+(j%(6 if ok else 5))*21;y=22+(j//(6 if ok else 5))*20
        sx=145+(i%10)*21;sy=22+(i//10)*20
        marks.append(f'<circle class="lease-mark {"success" if ok else "unrecorded"}" cx="{x}" cy="{y}" r="7" data-sx="{sx}" data-sy="{sy}" data-x="{x}" data-y="{y}"/>')
    return '<svg class="lease-morph" viewBox="0 0 450 225" role="img" aria-label="100 searches: approximately 57 with a recorded lease within one year and 43 without that outcome.">'+''.join(marks)+'</svg>'
housing[3]=re.sub(r'<div class="search-dots".*?</div>',lambda _:lease_graphic(),housing[3],flags=re.S)

def audit_graphic():
    marks=[]
    for i in range(320):
        group=0 if i<57 else 1 if i<87 else 2
        j=i if group==0 else i-57 if group==1 else i-87
        x=12+(j%20)*22; y=[38,110,182][group]+(j//20)*9
        sx=12+(i%20)*22; sy=38+(i//20)*14
        marks.append(f'<rect class="audit-mark group-{group}" x="{x}" y="{y}" width="14" height="6" rx="1" data-sx="{sx}" data-sy="{sy}" data-x="{x}" data-y="{y}"/>')
    return '<svg class="audit-morph" viewBox="0 0 450 300" role="img" aria-label="320 offices: 57 offered the selected clinician, 30 an alternate, and 233 no appointment."><g class="audit-labels"><text x="12" y="24">57 · Selected clinician</text><text x="12" y="97">30 · Alternate clinician</text><text x="12" y="169">233 · No appointment obtained</text></g>'+''.join(marks)+'</svg>'
health[2]=figure('03 / Same 320 offices','From directory to appointment', '<div class="big-number">27.2<span>%</span></div><p class="metric-caption">87 offices offered an appointment</p>'+audit_graphic(), '2023 calls · four cities · 57 + 30 = 87 offers out of 320 offices. The marks retain their identity as they regroup; their starting positions do not encode city. An offer is not completed treatment.', details(['Outcome','Offices'],[('Selected clinician',57),('Alternate clinician',30),('No appointment obtained',233)],'Mutually exclusive outcomes, not successive dropouts. JAMA, 2024.'))
health[3]=health[3].replace('class="bar-row "','class="bar-row "',1).replace('<span>New York City</span>','<span>New York City · local focus</span>')
health[3]=health[3].replace('<div class="calendar-bars">','<div class="nyc-finding"><strong>New York City</strong><span>36.3% offered an appointment</span><small>80 sampled offices · one Medicaid managed-care plan · 2023</small></div><div class="calendar-bars">')

def render(topic, route, figures, ids, labels, title, hero_title, dek, art, category, other):
    chapters=[]
    for idx,(scene,visual,sid) in enumerate(zip(COPY[topic],figures,ids)):
        sources=list(scene['sources'])
        if topic=='medicaid' and idx==1:
            sources=[{'label':'JAMA: audit methods and results','url':SOURCES['jama']}]
        sourcehtml=''.join(f'<a href="{e(s["url"],quote=True)}">{e(s["label"])} ↗</a>' for s in sources)
        paras=''.join(f'<div class="story-step" data-step="{j}"><p>{e(p)}</p></div>' for j,p in enumerate(scene['paragraphs']))
        chapters.append(f'<section class="story-chapter" id="{sid}" aria-labelledby="heading-{sid}"><div class="chapter-inner"><header class="chapter-heading"><p class="eyebrow">{idx+1:02} / {labels[idx]}</p><h2 id="heading-{sid}">{e(scene["title"].split(". ",1)[1])}</h2></header><div class="scene-grid"><div class="scene-copy">{paras}'+(f'<div class="scene-sources">{sourcehtml}</div>' if sources else '')+f'</div>{visual}</div></div></section>')
    navigation=''.join(f'<a href="#{sid}" aria-label="{i+1}. {label}">{i+1:02}<span class="nav-label"> {label}</span></a>' for i,(sid,label) in enumerate(zip(ids,labels)))
    reslinks=(['hud','furman','urban','trial'] if topic=='housing' else ['medicaid','jama','oig'])
    names={'hud':'HUD: voucher information and local assistance','furman':'Furman Center: success rates, methods and limitations','urban':'Urban Institute: landlord acceptance study','trial':'Creating Moves to Opportunity: trial and research materials','medicaid':'Medicaid.gov: managed care','jama':'JAMA: four-city appointment audit','oig':'HHS inspector general: networks and directory accuracy'}
    sources=''.join(f'<a href="{SOURCES[k]}">{names[k]} ↗</a>' for k in reslinks)
    html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, nofollow, noarchive"><meta name="googlebot" content="noindex, nofollow, noarchive"><title>{e(title)} | Available ≠ Accessible</title><meta name="description" content="{e(dek,quote=True)}"><meta property="og:title" content="{e(title,quote=True)}"><meta property="og:description" content="{e(dek,quote=True)}"><meta name="theme-color" content="#f8f6f0"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/collection.css?v=20260923-meet"><link rel="stylesheet" href="/access-stories.css?v=20260923"><script src="/collection.js?v=20260923-meet" defer></script><script src="/access-stories.js?v=1" defer></script><link rel="stylesheet" href="/story-refinements.css?v=20260923"><script src="/story-refinements.js?v=20260923" defer></script><link rel="stylesheet" href="/shared-footer.css?v=20260923"></head>
<body class="access-story {'health-story' if topic=='medicaid' else 'housing-story'}"><a class="skip" href="#main">Skip to story</a>{HEADER}<div class="story-progress" aria-hidden="true"><span></span></div><main id="main"><section class="story-hero"><div><p class="eyebrow">{category} / 4–6 min</p><h1>{hero_title}</h1><p class="dek">{e(dek)}</p><p class="byline">By <a href="/about/">Megan Quigley</a> · A synthesis of published research</p><a class="story-start" href="#{ids[0]}">Follow the story <span aria-hidden="true">↓</span></a></div><div class="hero-visual">{art}<p class="art-caption">{other['motif']}</p></div></section><div class="story-toolbar"><nav class="chapter-nav" aria-label="Story chapters">{navigation}</nav><button data-reading-toggle aria-pressed="false" hidden>Read without animation</button></div>{''.join(chapters)}
<section class="story-resources" id="sources"><p class="eyebrow">Keep looking</p><h2>The evidence behind the story.</h2><div class="resource-columns"><div><h3>Read the research</h3>{sources}<a href="/data/{topic}-access.json" download>Download chart data &amp; source notes ↓</a></div><div><h3>What this story can tell us</h3><p>{other['limit']}</p><p>Illustrations explain a process. They do not depict an interviewed person. Recommendations and editorial questions are labeled separately from measured results.</p><a href="/support/">Explore public-benefit support →</a></div></div><a class="story-next" href="{other['url']}"><span>Read another story</span>{other['title']} →</a></section></main><footer class="global-footer"><a href="/">Available ≠ Accessible</a><span>Independent research on public benefit access.</span></footer></body></html>'''
    path=DIST / 'case-studies' / route / 'index.html'
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(html)

render('housing','housing',housing,['approved','search','doors','lease','support','delivery'],['Benefit','Search','Barriers','Leases','Support','Delivery'], 'What does it take to find a home with a voucher?', 'What does it take<br>to find a home<br><em>with a voucher?</em>', 'Rental assistance is an important beginning. Follow the distance between approval and a signed lease.', HOUSE, 'Housing assistance', {'motif':'From approval to a front-door key','limit':'This story begins after a voucher is issued. The 2022 outcome is a one-year lease-up estimate at agencies passing data-quality checks. The landlord study and neighborhood trial have different populations and outcomes. None measures access among everyone eligible for housing assistance.','url':'/case-studies/health/','title':'What does it take to get mental-health care through Medicaid?'})
render('medicaid','health',health,['covered','listed','contacted','waiting','accountable'],['Coverage','Directory','Calls','Waits','Access'], 'What does it take to get mental-health care through Medicaid?', 'What does it take to get<br>mental-health care<br><em>through Medicaid?</em>', 'A provider directory makes care look findable. What happens when someone tries to use it?', HEALTH, 'Medicaid / mental-health care', {'motif':'From a coverage card to an appointment','limit':'This is an audit of adult psychiatric prescribing appointments in four cities, with calls in 2023. It is not a national rate, a study of every form of therapy, or a record of completed treatment. The study did not include a commercial-insurance comparison group.','url':'/case-studies/housing/','title':'What does it take to find a home with a voucher?'})

(DIST/'assets/housing-access.svg').write_text(HOUSE.replace(' aria-hidden="true"',''))
(DIST/'assets/medicaid-access.svg').write_text(HEALTH.replace(' aria-hidden="true"',''))
data={
 'housing':{'lease_up':{'years':dict(trend),'unit':'percent of new voucher searches leasing within one year','geography':'United States; 1,232 PHAs meeting data-quality standards','source':SOURCES['furman'],'locator':'Exhibit 3; sample discussion pages 8–9'},'landlord_denial':{'rates_percent':dict(denials),'report_year':2018,'denominator':'Voucher-acceptance tests included in each study location rate','source':SOURCES['urban'],'note':'Rounded rates; not lease-up outcomes or current local-law findings.'},'neighborhood_trial':{'control_percent':15,'support_percent':53,'outcome':'Moves to high-upward-mobility neighborhoods','geography':'Seattle and King County','denominator':'Families in each experimental group','source':SOURCES['trial'],'note':'Separate randomized trial, not overall lease-up rates.'}},
 'medicaid':{'audit':{'calls_year':2023,'publication_year':2024,'cities':['New York City','Los Angeles','Chicago','Phoenix'],'sample_per_city':80,'nyc_offered_percent':36.3,'offices':320,'selected_clinician':57,'alternate_clinician':30,'no_appointment_obtained':233,'appointment_offers':87,'offered_percent':27.2,'source':SOURCES['jama'],'scope':'Adult psychiatric prescribing appointments in selected Medicaid managed-care directories; not completed treatment.'},'waits':{'median_days':dict(waits),'observed_offers':70,'offers_without_wait_time':17,'denominator':'Offered selected or alternate appointments with recorded waits','source':SOURCES['jama'],'locator':'Figure 1 and Results'},'recommendation':{'text':'CMS should work with states to improve directory accuracy in Medicaid managed care.','source':SOURCES['oig'],'note':'Recommendation, not evidence of achieved improvement.'}}}
for topic,values in data.items():
    (DIST/'data'/f'{topic}-access.json').write_text(json.dumps(values,indent=2)+'\n')

# Update only the shared case-study menu on existing pages; preserve their bodies.
for path in DIST.rglob('*.html'):
    if path.parts[-3:-1] in [('case-studies','housing'),('case-studies','health')]:
        continue
    text=path.read_text()
    text=re.sub(r'(<details class="case-menu">.*?<div>).*?(</div></details>)',lambda m:m[1]+NAV+m[2],text,flags=re.S)
    footer = '<footer class="global-footer"><a href="/">Available ≠ Accessible</a><span>Independent research on public benefit access.</span></footer>'
    text=re.sub(r'<footer\b[^>]*>.*?</footer>',lambda _:footer,text,flags=re.S) if '<footer' in text else text.replace('</body>',footer+'</body>')
    if '/shared-footer.css' not in text:
        text=text.replace('</head>','<link rel="stylesheet" href="/shared-footer.css?v=20260923"></head>')
    path.write_text(text)

home=DIST/'index.html'
text=home.read_text()
start=re.search(r'<section\b[^>]*class="story-objects"[^>]*>',text).start()
end=text.index('</section>',start)+len('</section>')
text=text[:start]+'''<section class="story-objects" id="case-studies" aria-label="Case studies"><a class="story-object apple-link" href="/case-studies/wic/"><span class="sprite apples" aria-hidden="true"></span><span class="object-type">Food &amp; nutrition</span><h2>WIC</h2><p>What does it take to use WIC?</p><span class="object-action">Read the story ↗</span></a><a class="story-object" href="/case-studies/housing/"><img class="case-cover" src="/assets/housing-access.svg" alt="" width="190" height="230"><span class="object-type">Housing assistance</span><h2>Housing vouchers</h2><p>What does it take to find a home with a voucher?</p><span class="object-action">Read the story ↗</span></a><a class="story-object" href="/case-studies/health/"><img class="case-cover" src="/assets/medicaid-access.svg" alt="" width="190" height="230"><span class="object-type">Medicaid / mental health</span><h2>Access to care</h2><p>What does it take to get mental-health care through Medicaid?</p><span class="object-action">Read the story ↗</span></a></section>'''+text[end:]
if '/access-covers.css' not in text:
    text=text.replace('</head>','<link rel="stylesheet" href="/access-covers.css?v=1"></head>')
home.write_text(text)
print('Built housing and Medicaid stories, source data, illustrations, and collection links.')
