"""Build the independently authored WIC narrative. No legacy story imports."""
from pathlib import Path
import json, html
from wic_vectors import build_art, external, map_environment, store_environment, checkout_environment
build_art()
R=Path(__file__).resolve().parents[1]; OUT=R/'dist/case-studies/wic'
E=json.loads((OUT/'evidence.json').read_text())
def esc(x): return html.escape(str(x))
def art(i,cls='',atlas='maya'):
 return external(('s' if atlas=='situations' else '')+str(i),'art '+cls)
def situation(i,cls=''): return art(i,'situation '+cls,'situations')
def badge(t): return f'<span class="object-label">{t}</span>'
def pair(left,right,focus='both',labels=('Without WIC','With WIC')):
 return f'<div class="pair focus-{focus}"><div class="path left"><span class="path-label">{labels[0]}</span><div class="world">{left}</div></div><div class="path right"><span class="path-label">{labels[1]}</span><div class="world">{right}</div></div></div>'
def home(i=0,extra=''): return '<div class="room">'+art(4,'room-bg')+art(i,'person')+extra+'</div>'
def anchors(): return '<div class="anchors"><span>'+art(1)+'Without WIC</span><span>'+art(1)+'With WIC</span></div>'
def research(content):return '<div class="research">'+anchors()+content+'</div>'
def bars(rows,label,unit='%'):
 s=f'<div class="chart" role="img" aria-label="{esc(label + chr(59) + chr(32).join(f"{n}: {v:g}{unit};" for n,v in rows))}"><p class="chart-label">{label}</p><svg viewBox="0 0 660 {len(rows)*57+30}" aria-hidden="true">'
 for j,(n,v) in enumerate(rows):
  y=j*57+22;s+=f'<text x="0" y="{y+17}" class="bar-name">{n}</text><rect class="bar-track" x="167" y="{y}" width="398" height="25" rx="8"/><rect class="bar-fill" x="167" y="{y}" width="{v*3.98}" height="25" rx="8"/><text class="bar-value" x="583" y="{y+19}">{v:g}{unit}</text>'
 return s+'</svg><p class="axis-note">Common scale: 0–100%</p></div>'
def mapview(far=False):
 path='M55 225 L55 130 L150 130 L150 50 L270 50' if far else 'M55 225 L55 170 L120 170'
 return '<div class="map"><svg viewBox="0 0 330 270" role="img" aria-label="Illustrative neighborhood route; no mileage assigned"><path class="streets" d="M0 50H330 M0 130H330 M0 225H330 M55 0V270 M150 0V270 M270 0V270"/><path class="route" d="'+path+'"/><circle cx="55" cy="225" r="8"/><rect class="map-store" x="105" y="155" width="32" height="29"/><rect class="map-store" x="250" y="30" width="38" height="31"/><text x="15" y="257">Home</text><text x="70" y="207">Nearby store</text><text x="178" y="20">WIC store</text></svg>'+art(8,'map-traveler '+('far' if far else 'near'))+'</div>'
def shop(loop=False,step=0):
 return '<div class="shop">'+art(5,'floor')+f'<svg viewBox="0 0 320 320" aria-hidden="true"><path class="cart-route" d="'+('M155 284 L155 70 L200 70 L200 223 L105 223 L105 63 L245 63 L245 263 L158 263' if loop else 'M155 284 L155 70 L245 70 L245 263 L158 263')+'"/></svg>'+art(8,f'cart cart-{step}')+'</div>'
def receipt(wic=False):
 lines=[('Eligible food','WIC'),('Produce allowance','WIC'),('Rejected item','My money'),('Other purchases','My money')] if wic else [('Groceries','My money'),('Produce','My money'),('Other purchases','My money')]
 return '<div class="receipt"><span class="receipt-title">'+('Two ways to pay' if wic else 'One grocery bill')+'</span>'+''.join(f'<p><span>{a}</span><b>{b}</b></p>' for a,b in lines)+'<small>Schematic receipt · no invented prices</small></div>'
def produce(n):
 total=min(n,12)*52+max(n-12,0)*26
 return research(f'<div class="produce" data-months="{n}"><p class="chart-label">Available produce benefits · constant FY2026 rates</p><div class="money"><span>Without WIC<strong>$0</strong></span><span>With WIC<strong>$'+f'{total:,}'+'</strong></span></div><div class="month-grid">'+''.join(f'<i class="month {"filled" if j<n else ""} {"maternal" if j<12 else "child"}" title="Month {j+1}"></i>' for j in range(60))+'</div><div class="legend"><span>12 months × $52 for Maya</span><span>48 months × $26 for her child</span></div><p class="axis-note">Each square is one month. This is availability, not redemption.</p></div>')
scenes=[]
def scene(title,time,beats):scenes.append({'title':title,'time':time,'beats':beats})
def beat(visual,caption,who='Maya · both paths',note='',source=None):return dict(visual=visual,caption=caption,who=who,note=note,source=source)
scene('Same mother. Same baby.','A new baby',[
 beat(pair(home(),home()),'My baby is here. He is crying. I am exhausted.'),
 beat(pair(situation(0),situation(0)),'Everyone says to sleep when he sleeps. Apparently that is also when I’m supposed to do everything else.'),
 beat(pair(home(),home()),'Same baby. Same income. Same need for food. Two ways the next five years could go.','One mother · two paths','Maya and the dialogue are illustrative, not a reported individual. Both paths begin with the same eligible New York family.')])
scene('“Have you tried WIC?”','A friend’s text',[
 beat(pair(situation(0),situation(1),'right'),'“Have you tried WIC?”','With WIC · a friend'),
 beat(pair(home(),'<div class="phone-scene">'+art(10,'phone')+'<div class="messages"><p class="message incoming">Have you tried WIC?</p><p class="message outgoing">Is that food stamps?</p></div></div>','right'),'“Is that food stamps?”','With WIC · Maya'),
 beat(pair(home(),'<div class="phone-scene">'+art(10,'phone')+'<div class="messages"><p class="message incoming">No, it’s for you and the baby.</p><p class="message incoming">You should check.</p></div></div>','right'),'Thank God she said something. I had no idea.','With WIC · Maya','WIC provides specified foods, nutrition education, breastfeeding support, and referrals.','ny'),
 beat(pair(situation(0),situation(1),'left'),'I know about food stamps. We have Medicaid. WIC never comes up.','Without WIC · Maya','In one small study, 8 of 10 participant interviewees learned about WIC through family or friends. This is not a national estimate.','referral')])
scene('“Now I have to apply.”','Before the help arrives',[
 beat(pair(home(),situation(2),'right'),'Ugh. First, my ID.','With WIC · Maya'),
 beat(pair(home(),'<div class="paperwork">'+art(11)+'<span class="paper">ID</span><span class="paper">Address</span><span class="paper">Medicaid</span></div>','right'),'Then my address and Medicaid information. Medicaid establishes income eligibility. It doesn’t enroll me in WIC.','With WIC · Maya','WIC still requires an eligibility assessment, including nutrition risk.','ny'),
 beat(pair(situation(0),situation(3),'right'),'There’s still an appointment to arrange. A phone appointment can save a trip—but I still need time for the call.','With WIC · Maya','New York offers phone appointments; circumstances and required documentation vary.','ny'),
 beat(pair(home(),situation(8)),'I’m fully breastfeeding. My package includes $52 a month for produce, plus other foods. Okay. That would help.','With WIC · Maya','FY2026 rate for fully breastfeeding participants. This is Maya’s allowance, not a newborn’s produce allowance.','rates')])
scene('The help reaches people unevenly.','From one family to the country',[
 beat(research(bars([('New York',62.4),('United States',56.1)],'Share of eligible people participating · 2023')),'The first hurdle is getting through the door.','A wider view','Average-month estimates; women, infants, and children eligible for WIC.','coverage'),
 beat(research(bars([('Vermont',79.6),('New York',62.4),('United States',56.1),('Louisiana',41.3)],'Share of eligible people participating · 2023')),'The same federal program. Very different reach.','A wider view','Vermont and Louisiana have the highest and lowest point estimates among the 50 states. Estimates have uncertainty; Vermont’s interval is especially wide.','coverage'),
 beat(research(bars([('Vermont',79.6),('New York',62.4),('United States',56.1),('Louisiana',41.3)],'Share of eligible people participating · 2023')),'Would a referral that leads somewhere—or an appointment that fits my life—change what happens next?','Maya · a question for the system','These are plausible explanations, not demonstrated causes of the state differences.','coverage')])
scene('Same neighborhood. Different trip.','Getting to a store',[
 beat(pair(mapview(),mapview()),'The baby is finally settled. I just want to get the groceries done.','Maya · both paths','Both maps are illustrative. No mileage or actual neighborhood is implied.'),
 beat(pair(mapview(),mapview(True),'right'),'My nearby store doesn’t take WIC. I check the locator. It’s a longer trip with the baby.','With WIC · Maya','Illustrative route, not a measured trip.'),
 beat(pair(situation(4),situation(4),'left'),'I go where I usually shop. I choose what I can afford.','Without WIC · Maya'),
 beat(research(bars([('Louisiana',56),('United States',40),('Vermont',30),('New York',19)],'Families without convenient WIC retailer access')),'Having benefits and having a place to use them are two different things.','A wider view','FY2022 retailers; low-income families with children under 5 estimated from 2015–19 ACS data. Threshold: more than 1 mile urban or 10 miles rural.','access'),
 beat(research('<div class="chart scatter"><p class="chart-label">Across 50 states: farther from stores, less reach</p><svg viewBox="0 0 640 330" role="img" aria-label="State access and coverage scatter plot, Pearson correlation minus 0.47"><path class="axis" d="M60 20V275H610"/>'+''.join(f'<circle cx="{60+r["without_convenient_access_pct"]*8.2}" cy="{275-(r["eligible_covered_pct"]-30)*4.5}" r="5"><title>{r["state"]}: {r["without_convenient_access_pct"]:g}% without access, {r["eligible_covered_pct"]:g}% covered</title></circle>' for r in E['states'])+'<text x="65" y="18">WIC coverage (%)</text><text x="12" y="57">80</text><text x="12" y="147">60</text><text x="12" y="237">40</text><text x="52" y="297">0</text><text x="212" y="297">20</text><text x="377" y="297">40</text><text x="541" y="297">60</text><text x="160" y="325">Without convenient access (%)</text></svg></div>'),'States with more families far from a WIC store tend to reach fewer eligible people.','A wider view','Reproduced Pearson r = −0.47 across 50 states. Different years and populations; association does not establish causation.','correlation')])
scene('“Right food. Wrong size.”','Inside the grocery store',[
 beat(pair(shop(),shop()),'This is not one grocery budget. It’s quantities of certain foods, plus dollars for produce.','With WIC · Maya','Food packages vary by participant. Illustrations do not identify approved brands or sizes.','ny'),
 beat(pair(shop(False,1),shop(True,1),'right'),'Right food. Wrong size. Back down the aisle.','With WIC · Maya'),
 beat(pair(situation(5),situation(5),'left'),'I put something back. I’m watching what’s left in my account.','Without WIC · Maya'),
 beat(pair(shop(False,2),shop(True,3),'right'),'I can’t swap the milk allowance for more fruit. And now the baby is crying.','With WIC · Maya','Specified food quantities and the produce dollar allowance are separate.','ny'),
 beat(pair(situation(5),'<div class="food-rules">'+art(13)+badge('Food quantities')+art(9)+badge('Produce dollars')+'</div>','right'),'The card replaced paper checks. It didn’t remove the rules.','With WIC · Maya')])
scene('One item at a time.','At the checkout',[
 beat('', 'First, the eggs. One dozen. The right size this time.','With WIC · Maya'),
 beat('', 'Bananas. Two pounds. That comes out of my produce dollars.','With WIC · Maya'),
 beat('', 'Then the carrots. More food coming home.','With WIC · Maya'),
 beat('', 'Peanut butter. That one goes through, too.','With WIC · Maya'),
 beat('', 'The rice won’t go through. I picked white rice. WIC covers brown rice.','With WIC · Maya'),
 beat('', 'I pay the $1.77. WIC covered $5.97 of this $7.74 basket.','With WIC · Maya'),
 beat('', 'Without WIC, the same basket takes $7.74 from the money I already have.','Without WIC · Maya')])
scene('On the card. In the kitchen.','Month after month',[
 beat(pair(situation(8),situation(8),'right'),'Some months I make the trip. The food I bring home helps.','With WIC · Maya'),
 beat(pair(situation(8),'<div class="expiry">'+art(12)+'<span class="expiry-stamp">MONTH ENDS</span>'+art(9,'fading-food')+'</div>','right'),'Some months there’s still food on my benefits when they expire. I meant to go back. Then something else happened.','With WIC · Maya','Unused monthly benefits do not roll over. No redemption percentage is assigned to Maya.','ny'),
 beat(research('<div class="redemption"><p class="chart-label">Southern California · 2019–2023 study</p><strong class="big-number">30.4%</strong><div class="portion"><span style="width:30.4%"></span></div><p>redeemed less than 70%<br>of the fruit-and-vegetable benefit</p></div>'),'The amount on the card and the amount in the kitchen aren’t always the same.','A wider view','365,738 certification periods in the study’s fruit-and-vegetable analysis. This is a share of periods, not the share of dollars lost.','redemption')])
scene('“Can I deal with this today?”','His first birthday',[
 beat(pair(situation(11),situation(11)),'His first birthday. Another grocery list.','Maya · both paths'),
 beat(pair(situation(11),situation(9),'right'),'The renewal reminder arrives. The appointment conflicts with work. I put it aside.','With WIC · Maya'),
 beat(pair(situation(11),'<div class="paperwork">'+art(12)+badge('Office closed')+art(11)+badge('Documents to update')+'</div>','right'),'Tomorrow, I remember after the office closes. Then I have to check which documents they need.','With WIC · Maya'),
 beat(pair(situation(11),situation(9),'right'),'I’m not deciding we don’t need the food. I just can’t deal with this today.','With WIC · Maya'),
 beat(pair(situation(11),situation(10),'right'),'This time, I call before the deadline. I find an appointment I can manage. I renew.','With WIC · Maya','This renewal sequence is illustrative. Certification schedules and requirements vary.')])
scene('Four more years.','Growing up together',[
 beat(pair(situation(12),situation(12)),'He’s two. More groceries. Another appointment.','Maya · both paths'),
 beat(pair(situation(13),situation(13)),'He’s three. I know the foods that work for us. I still have to keep coming back.','With WIC · Maya'),
 beat(pair(situation(14),situation(14)),'He’s four. His need for food hasn’t expired with the paperwork.','Maya · both paths'),
 beat(research('<div class="cohort"><p class="chart-label">A historical enrollment cohort · through 54 months</p><strong class="big-number">43.5%</strong><div class="portion"><span style="width:43.5%"></span></div><p>participated consistently</p><p class="small-stat">56.5% did not participate consistently</p></div>'),'Not everyone stays connected all the way through.','A wider view','USDA’s 2013 enrollment cohort, weighted mother–child pairs. Inconsistent includes leaving or intermittent participation; it is not a single-renewal dropout rate.','cohort'),
 beat(research(bars(list(zip(['Infants','Age 1','Age 2','Age 3','Age 4'],E['age_coverage_2023'])),'Eligible people reached · separate age groups, 2023')),'Nationally, WIC reaches fewer eligible children at each older age.','A wider view','Average-month coverage in 2023. These are separate age groups, NOT the same children followed as they leave.','coverage')])
scene('What accumulates.','One month at a time',[
 beat(produce(1),'One month: up to $52 for produce while I’m fully breastfeeding.','With WIC · Maya','Available produce benefits only; other WIC foods are additional.','rates'),
 beat(produce(12),'Twelve months: up to $624.','With WIC · Maya','Assumes a full year of maternal eligibility at the FY2026 fully breastfeeding rate.','rates'),
 beat(produce(24),'Then $26 a month for my child. One year adds $312.','With WIC · Maya','The child illustration starts at age 1 and continues until the fifth birthday.','rates'),
 beat(produce(36),'Two child years add $624 to that first year of help.','With WIC · Maya','Available allowance, not actual food redeemed or guaranteed savings.','rates'),
 beat(produce(48),'Three child years add $936.','With WIC · Maya','Holds FY2026 rates constant; not a forecast of future benefit levels.','rates'),
 beat(produce(60),'Four child years, plus my breastfeeding year: up to $1,872 in available produce benefits.','With WIC · Maya','12 × $52 + 48 × $26 = $1,872. Actual redeemed value is lower whenever benefits go unused.','rates')])
scene('What the help can change.','His fifth birthday',[
 beat(research('<div class="diet"><p class="chart-label">Diet quality at age 3 · observational study</p><strong class="big-number">+3.6 <small>points</small></strong><div class="difference"><span>WIC in first year only</span><b>→</b><span>Continued into third year</span></div><p>Adjusted difference on the 100-point<br>Healthy Eating Index–2015</p></div>'),'The years after infancy matter, too. Staying into the third year was associated with higher diet-quality scores.','A wider view','Association, not a causal estimate or a forecast for Maya’s child. Absolute group scores are not depicted.','diet'),
 beat(pair(situation(15),situation(15)),'The same fifth birthday. A different experience of getting help.','Maya · both paths','We cannot infer different health outcomes for these illustrative children.'),
 beat(pair(situation(15),situation(15),'left'),'Tell me about WIC. Help me book the first appointment. Follow up when the referral goes nowhere.','Without WIC · Maya'),
 beat(pair(situation(15),situation(15),'right'),'Give me a renewal I can manage. A nearby store. Clear labels. Help when something won’t scan.','With WIC · Maya'),
 beat(pair(situation(15),situation(15)),'Getting help should take less work.','The work of getting help')])
BASKET=json.loads((OUT/'basket.json').read_text())
ENVIRONMENTS={4:map_environment(),5:store_environment(),6:checkout_environment(BASKET['items'])}
SOURCES={
'ny':('New York WIC: applying and using benefits','https://www.health.ny.gov/prevention/nutrition/wic/how_to_apply.htm','Income eligibility is only one component of WIC certification. See also <a href="https://www.health.ny.gov/prevention/nutrition/wic/faqs.htm">New York WIC FAQs</a>, <a href="https://www.mhhc.org/our-services/mhhc-wic-program/">MHHC’s current phone appointment options</a>, and <a href="https://www.ccf.ny.gov/application/files/2617/1294/8575/WICSNAPSummerMeals04112024.pdf">New York’s benefit-expiration guidance</a>. Product illustrations are schematic.'),
'referral':('Qualitative referral study · 2026','https://www.frontiersin.org/journals/health-services/articles/10.3389/frhs.2026.1707744/full','Ten participant interviewees recruited through a New Hampshire WIC agency; the broader study includes New Hampshire and Vermont staff. Interviews February–April 2024; 8 of 10 learned of WIC from family/friends. Not nationally representative.'),
'coverage':('USDA · 2023 eligibility and coverage','https://fns-prod.azureedge.us/sites/default/files/resource-files/wic-eer2023-report.pdf','Tables 3.1, 3.5 and 3.7. Coverage = average-month participants divided by eligible people. 95% intervals: Vermont 65.1–94.2%, New York 61.0–63.8%, Louisiana 39.9–42.7%, national 54.5–57.6%. Age values are cross-sectional.'),
'access':('USDA · WIC retailer access, Table A.20','https://fns-prod.azureedge.us/sites/default/files/resource-files/wic-accessPart1-finalReport.pdf','FY2022 retailers; 2015–2019 ACS low-income families with children under 5 are a proxy for WIC-eligible families. Convenient access is within 1 mile in urban areas or 10 miles in rural areas. Rounded table percentages used.'),
'correlation':('Reproduced 50-state comparison','evidence.json','Pearson r = '+str(round(E['pearson_r'],8))+'. Join by state; exclude DC and Puerto Rico. Equal weight for each state; rounded access percentages from Table A.20 and 2023 coverage from Table 3.5. Ecological, cross-year association; no causal interpretation. Source transcription and Python reproduction are saved with this branch.'),
'rates':('USDA · FY2026 produce allowance','https://www.usda.gov/sites/default/files/guidance-documents/fna.wic-2026-2-cvvb-amounts.pdf','October 1, 2025–September 30, 2026: $52/month fully breastfeeding; $26/month child. Illustration assumes 12 fully breastfeeding months plus 48 child months, continuous eligibility and constant FY2026 rates. Excludes other foods and the optional juice substitution. Not actual redemption, total WIC value, guaranteed savings, or forecast.'),
'redemption':('JAMA Network Open · benefit redemption','https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2842211','Southern California, November 2019–June 2023 records; children aged 0–3 at certification in November 2019–June 2022. 188,368 participants. Table 2: 254,506 of 365,738 fruit-and-vegetable certification periods redeemed at least 70% (69.6%); the complement is 30.4%. Unit is certification periods, not people or lost dollars.'),
'cohort':('USDA · Infant and Toddler Feeding Practices Study, Year 5','https://fns-prod.azureedge.us/sites/default/files/resource-files/WIC-ITFPS2-Year5Report.pdf','2013 enrollment cohort. Consistent participation refers to mother or child receipt during years 1 and 2 and subsequent observed months through 54 months. Weighted 43.5% consistent, 56.5% not consistent. Not a current national count or a renewal dropout estimate.'),
'diet':('Borger et al. · WIC participation and diet quality','https://pubmed.ncbi.nlm.nih.gov/35277313/','Adjusted observational comparison at age 3: participation in only the first year was associated with a 3.6-point lower Healthy Eating Index–2015 score than participation into the third year. Scale is 0–100. Does not establish causation.')}
SOURCES['shopping']=('The checkout basket · prices and food rules','basket.json','Walmart online prices accessed September 24, 2026: 12 Great Value large white eggs $1.67; bananas 2 lb at $0.50/lb, $1.00; 1 lb baby carrots $1.32; Great Value creamy peanut butter 16 oz $1.98; Great Value white rice 32 oz $1.77. Total $7.74; four covered items $5.97; white rice $1.77 paid separately. Public listings are a price snapshot, not an Albany-store quote. Assumes an authorized store and sufficient matching food benefits. Individual product URLs, sizes, quantities, and NY food-rule sources are in the linked data file.')
SOURCES['map']=('Albany street map · U.S. Census Bureau','https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Transportation/MapServer','Street geometry downloaded September 24, 2026 from TIGERweb local and secondary road layers. Routes follow connected street vertices. The story’s home and generic shop endpoints are narrative locations; no household address, reported trip, retailer status, or travel-time estimate is asserted. Raw geometry and route calculations are saved with the project.')
parts=[]
for i,s in enumerate(scenes):
 frames=[]
 for j,b in enumerate(s['beats']):
  source=f' <a href="#source-{b["source"]}" class="source-link">Notes ↗</a>' if b['source'] else ''
  frames.append(f'<div class="frame" data-beat="{j}"><div class="visual">{b["visual"]}</div><div class="caption"><p class="speaker">{esc(b["who"])}</p><p class="line">{esc(b["caption"])}</p><p class="disclosure">{source}</p></div></div>')
 parts.append(f'<section class="scene {"immersive" if i in ENVIRONMENTS else ""}" id="scene-{i+1}" data-count="{len(frames)}" style="--beats:{len(frames)}" aria-labelledby="title-{i+1}"><div class="sticky"><header class="scene-heading"><p>{i+1:02d} / 12 <span>{esc(s["time"])}</span></p><h2 id="title-{i+1}">{s["title"]}</h2></header>{ENVIRONMENTS.get(i, "")}<div class="frames">'+''.join(frames)+f'</div><div class="beat-progress" aria-hidden="true">'+''.join('<i></i>' for _ in frames)+'</div></div></section>')
end='<section class="sources" id="sources"><p class="eyebrow">Behind the story</p><h2>Sources & methodology</h2><p>Narrative and dialogue written for this project. Research, calculations, prices, and map data are documented below.</p>'+''.join(f'<article id="source-{k}"><h3><a href="{v[1]}">{v[0]}</a></h3><p>{v[2]}</p></article>' for k,v in SOURCES.items())+'<article><h3>Artwork & approach</h3><p>Original SVG character, environment, food, and chart drawings; Census street geometry; scroll-driven movement and receipt calculations. Inspired by character continuity in The Pudding’s <a href="https://pudding.cool/2024/03/teenagers/">Teenagers</a>, conversational pacing in <a href="https://pudding.cool/2025/02/middle-school/">Middle School</a>, and transaction-to-population storytelling in <a href="https://pudding.cool/2022/12/yard-sale/">Yard Sale</a>.</p></article><p class="end-credit">A visual story by Megan Quigley</p></section>'
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, nofollow, noarchive"><meta name="googlebot" content="noindex, nofollow, noarchive"><meta name="theme-color" content="#f8f6f0"><title>The work of getting help — WIC</title><meta name="description" content="Follow one mother down two paths to see what WIC changes—and how much work it takes to keep getting it."><link rel="stylesheet" href="story.css?v=20260924-3"><script type="module" src="story.js?v=20260924-3"></script></head><body><main><section class="opening" aria-label="Available does not equal accessible"><div class="opening-pin"><div class="equation"><span class="available">Available</span><span class="symbol">≠</span><span class="accessible">Accessible</span></div><p class="scroll-cue">A story about the distance between the two<br><span>Scroll to begin ↓</span></p></div></section><section class="introduction"><p class="eyebrow">Available ≠ Accessible · WIC</p><h1>The work<br>of getting help</h1><p class="dek">WIC helps families afford nutritious food. Follow one mother down two paths to see what the help changes—and how much work it takes to keep getting it.</p><p class="byline">By Megan Quigley</p><p class="intro-tail">One mother. Two paths. Five years.</p></section>'''+''.join(parts)+end+'<script id="basket-data" type="application/json">'+json.dumps(BASKET['items'])+'</script></main></body></html>'
(OUT/'index.html').write_text(page)
(OUT/'evidence-metadata.json').write_text(json.dumps({k:{'title':v[0],'url':v[1],'method':v[2]} for k,v in SOURCES.items()},indent=2)+'\n')
(OUT/'scene-manifest.json').write_text(json.dumps([{'title':s['title'],'beats':[{'caption':b['caption'],'speaker':b['who'],'source':b['source']} for b in s['beats']]} for s in scenes],indent=2)+'\n')
print(f'Built {len(scenes)} scenes, {sum(len(s["beats"]) for s in scenes)} deterministic beats')
